name: deploy resources to AWS

on:
    push:
        branches: main
    # pull_request:
    #     branches: main
jobs:
    terraform:
        name: terraform lint, security check and deploy
        runs-on: ubuntu-latest

        env:
            AWS_REGION: 'us-east-1'
            TF_VERSION: '1.4.0'
            TFLINT_VERSION: '0.46.1'
            TFSEC_VERSION: '1.28.1'
        steps:
            - name: checkout to gthub repo
              uses: actions/checkout@v2

            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
            - name: setup  terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION}}
            # - name: Install TFLint
            #   run: |
            #       curl -L https://github.com/terraform-linters/tflint/releases/download/v${{env.TFLINT_VERSION}}/tflint_linux_amd64
            #       curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            #       unzip tflint.zip -d /usr/local/bin/
            #       tflint --version
            # - name: Install TFSec
            #   run: |
            #       curl -L https://github.com/tfsec/tfsec/releases/download/v${{env.TFSEC_VERSION}}/tfsec-linux-amd64
            #       chmod +x tfsec
            #       mv tfsec /usr/local/bin/
            #       tfsec --version
            - name: format Terraform files
              id: fmt_recursive
              run: terraform fmt -recursive
            - name: Terraform format
              id: fmt
              run: terraform fmt -check

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            # - name: TFLINT
            #   run: |
            #       tflint --init
            #       tflint

            # - name: Terraform Security Scan
            #   run: tfsec .

            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color  -out=tfplan

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan
